# Generated by Django 4.2.1 on 2023-06-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='username',
            field=models.CharField(max_length=16),
        ),
    ]
