# Generated by Django 4.2.1 on 2023-06-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_alter_passwords_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passwords',
        ),
    ]
