# Generated by Django 4.2.1 on 2023-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('password', '0003_delete_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('ste', models.CharField(default='hi', max_length=150)),
                ('password', models.CharField(default=None, max_length=16)),
                ('logo', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
