# Generated by Django 4.2.1 on 2023-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0005_alter_passwords_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
