# Generated by Django 4.2.1 on 2023-06-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0006_alter_passwords_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='logo',
            field=models.CharField(default='https://images.unsplash.com/photo-1603366615917-1fa6dad5c4fa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', max_length=500),
        ),
    ]
